spring:
  profiles:
    active: dev
  redis:
    host: 172.31.118.23
    password: 123456
    port: 6379
server:
  port: 80
  #address: localhost
#mybatis配置
mybatis:
  config-locations: classpath:mybatis-config11.xml
  mapper-locations: classpath:com/talelife/edu/engdict/mapper/*.xml
  type-aliases-package: com.talelife.edu.engdict.model11
  configuration:
    cache-enabled: false
#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params-count: countSql
#日志配置
logging:
  file: engdict.log
  level.org.springframework.web: debug
  level.org.springframework.transaction: debug
  level.org.mybatis: debug
  level.com.talelife.edu.engdict: debug
  debug: false
#redis session
redis:
  #hostName: 120.25.208.44
  host: 172.31.118.23
  password: 123456
  port: 6379
  timeout: 10000


---
spring:
  profiles: dev
  #spring数据源配置
  datasource:
    url: jdbc:mysql://www.talelife.com:3306/engdict?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    #指定数据连接沲
    type: com.alibaba.druid.pool.DruidDataSource
---
spring:
  profiles: prd
  #spring数据源配置
  datasource:
    url: jdbc:mysql://www.talelife.com:3306/engdict?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    #指定数据连接沲
    type: com.alibaba.druid.pool.DruidDataSource